title: Sanganaka Lab

collections:
  team:
    output: true

# optional: global permalink for members
defaults:
  - scope:
      path: "_team"
      type: "team"
    values:
      layout: member
      permalink: "/team/:name/"
